// Turn content/ into one typed module (src/generated.ts) that any bundler can import.
// Run after editing content: `pnpm --filter @xq/content generate` (a test checks it is current).
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = (p) => fileURLToPath(new URL(`../../../content/${p}`, import.meta.url));
const units = JSON.parse(readFileSync(root("lessons/units.json"), "utf8"));
const lessons = readdirSync(root("lessons"))
  .filter((f) => f.endsWith(".json") && f !== "units.json")
  .sort()
  .map((f) => JSON.parse(readFileSync(root(`lessons/${f}`), "utf8")));
const bots = JSON.parse(readFileSync(root("bots/bots.json"), "utf8"));
const puzzles = readFileSync(root("puzzles/puzzles.jsonl"), "utf8")
  .split("\n")
  .filter(Boolean)
  .map((l) => JSON.parse(l));

/** Lessons and bots: small, imported by every page. */
export function render() {
  return [
    "// GENERATED by scripts/generate.mjs from content/. Do not edit by hand.",
    'import type { BotConfig } from "@xq/bots";',
    'import type { Lesson, Unit } from "@xq/lessons";',
    "",
    `export const UNITS: Unit[] = ${JSON.stringify(units)};`,
    `export const LESSONS: Lesson[] = ${JSON.stringify(lessons)};`,
    `export const BOTS: BotConfig[] = ${JSON.stringify(bots)};`,
    "",
  ].join("\n");
}

/** Puzzles: large, in their own module so bundlers load them only on puzzle pages. */
export function renderPuzzles() {
  return [
    "// GENERATED by scripts/generate.mjs from content/puzzles/puzzles.jsonl. Do not edit by hand.",
    'import type { Puzzle } from "@xq/puzzles";',
    "",
    `export const PUZZLES: Puzzle[] = ${JSON.stringify(puzzles)};`,
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(fileURLToPath(new URL("../src/generated.ts", import.meta.url)), render());
  writeFileSync(fileURLToPath(new URL("../src/puzzles.generated.ts", import.meta.url)), renderPuzzles());
  console.log(`content: ${units.length} units, ${lessons.length} lessons, ${bots.length} bots, ${puzzles.length} puzzles`);
}
