// Generated by scripts/crosscheck.mjs (counts from Fairy-Stockfish "go perft").
export const PERFT_CASES: { name: string; fen: string; counts: number[] }[] = [
  {
    "name": "stalemate (black to move, no legal move)",
    "fen": "4k4/9/6N2/9/9/9/9/9/3R1R3/3K5 b - - 0 1",
    "counts": [
      0,
      0,
      0
    ]
  },
  {
    "name": "checkmate (chariot on the back rank)",
    "fen": "R3k4/9/6N2/9/9/9/9/9/3R1R3/3K5 b - - 0 1",
    "counts": [
      0,
      0,
      0
    ]
  },
  {
    "name": "pinned by the flying general",
    "fen": "4k4/9/9/9/4c4/9/9/4R4/9/4K4 w - - 0 1",
    "counts": [
      11,
      94,
      1682
    ]
  },
  {
    "name": "cannon screens and horse legs",
    "fen": "r1bakab1r/9/1cn3nc1/p1p1C1p1p/9/9/P1P1P1P1P/2N4C1/9/R1BAKABNR b - - 0 1",
    "counts": [
      35,
      1376,
      51397
    ]
  },
  {
    "name": "crossed soldiers",
    "fen": "3k5/4a4/2P1P1P2/9/4p4/2p6/9/9/4A4/3AK4 w - - 0 1",
    "counts": [
      13,
      109,
      1336
    ]
  },
  {
    "name": "random game 1",
    "fen": "4ka3/8r/4ban2/2p1p1p2/p5Rcp/P2rP3P/1cP1NNP2/4BA3/4A4/2R1K1B2 w - - 11 35",
    "counts": [
      28,
      1663,
      45435
    ]
  },
  {
    "name": "random game 2",
    "fen": "3a1k1C1/3r5/b1nrba3/p5p1p/1Pp1p2P1/4C4/2P1P1Pc1/2N3N2/2R2K3/1cBA1AB1R b - - 22 27",
    "counts": [
      42,
      1924,
      82702
    ]
  },
  {
    "name": "random game 3",
    "fen": "rn1akab1r/9/1c2b3n/p1p1p1p1p/2c6/4C3P/P3P1P2/1C6N/9/RNBAKAB1R w - - 4 6",
    "counts": [
      40,
      1442,
      56169
    ]
  },
  {
    "name": "random game 4",
    "fen": "2bakab1r/3Cn2R1/n8/p3p1p1p/1r7/PC4B2/2p1P1P2/9/1RN1Ac3/1cBAK4 b - - 21 31",
    "counts": [
      45,
      2041,
      88469
    ]
  },
  {
    "name": "random game 5",
    "fen": "1n1akarn1/4r4/8b/p3p3p/2b6/6C2/Pc2P1P1P/B3B1R1c/7C1/1N1AKA1N1 b - - 1 26",
    "counts": [
      38,
      1675,
      65656
    ]
  }
];
